name: Lint Markdown

on:
  push:
    paths:
      - 'README.md'
  pull_request:
    paths:
      - 'README.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: avto-dev/markdown-lint@v1
      with:
        config: '.markdownlint.json'